name: domain
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'


environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  common:
    path: ../common

  get_it: ^7.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner:
