name: common
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  domain:
    path: ../domain
  data:
    path: ../data
  depreciation_fixed_assets_app:
    path: ../app_depreciation_fixed_assets_app

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
