name: common
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  domain:
    path: ../domain
    
  depreciation_fixed_assets_app:
    path: ../app_depreciation_fixed_assets_app
  easy_localization: ^3.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
