name: common
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  domain:
    path: ../domain
  data:
    path: ../data
  depreciation_fixed_assets_app:
    path: ../app_depreciation_fixed_assets_app
  easy_localization: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
