name: depreciation_fixed_assets_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain
  data:
    path: ../data
  common:
    path: ../common

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  get_it: ^7.2.0
  json_annotation: ^4.6.0
  flutter_bloc: ^8.1.2
  easy_localization: ^3.0.1
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.9
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/ru-RU.json
    - assets/i18n/ro-RO.json

  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
